### ISSUE TITLE
No pings are sent from a Normal Window if a Private one is opened right after the experiment is installed

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/taar-experiment-v3-shield-study#43] opened 2018-07-11 12:01 UTC
[Affected versions]:
- Firefox 61.0.1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- You can download the latest version of the "TAAR v3" add-on from here:https://bugzilla.mozilla.org/show_bug.cgi?id=1469546.
- Create the following prefs in the "about:config" page:
"shieldStudy.logLevel" as string and set it to "All";
"extensions.taarexpv3_shield_mozilla_org.test.variationName" as string and set it to "control", "intervention-a" or "intervention-b"

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Install the TAAR add-on from Bug 1469546 and open a Private Window.
3. Switch back to the Normal Window and navigate to a website (https://www.wikipedia.org/).
4. Click 3 different links (one after another) from the website's content (without leaving the current active tab).
5. Navigate to the "about:telemetry" page and select the "Archived ping data" ("shield-study-addon" ping type).
6. Click the "Raw JSON" button.
7. Observe the last sent ping.

[Expected result]:
- The doorhanger trigger ping is displayed.

[Actual results]:
- The installation trigger ping is displayed.

[Notes]:
- Also, the add-ons installation pings are not sent. You don't need to follow the steps above, it's only necessary to have a Private Window opened and anytime you install add-ons from the Normal one, the pings are not sent.
- This issue is also reproducible on TAAR 3.0.1.
- Here is a screen recording with the issue:
![taar 3 - no telemetry pings](https://user-images.githubusercontent.com/31244235/42569854-a165d756-851a-11e8-9790-10b838d3991e.gif)

**Comment by motin** [comment] 2018-07-11 17:10
Closing this since it is expected behavior, documented under "Peculiarities" in https://github.com/motin/taar-experiment-v3-shield-study/blob/develop/docs/TESTPLAN.md#peculiarities
Ping @mlopatka fyi

**Closed as completed by motin** 2018-07-11 17:10 UTC
